version: '3.8'

services:
  codica:
    container_name: main
    build:
      context: .
    env_file:
      - .docker.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:codica
    depends_on:
      - postgres
    restart: always
  db:
    container_name: postgres
    image: postgres:14.0-alpine
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    restart: always